using Bogus;
using TypeFlow.Core.Entities;

namespace TypeFlow.Infrastructure.Seed
{
    public static class SeedingHelper
    {
        public static List<TypingChallenge> GetTypingChallenges()
        {
            var texts = GetTexts();

            int counter = -1;
            var faker = new Faker<TypingChallenge>()
                .RuleFor(x => x.CreatedAt, x => DateTime.UtcNow)
                .RuleFor(x => x.Id, x => Guid.NewGuid())
                .RuleFor(x => x.Text, x =>
                {
                    counter++;
                    return texts[counter];
                });

            var challenges = faker.Generate(texts.Length);
            return challenges;
        }

        private static string[] GetTexts()
        {
            return [
                "Technology has transformed the education sector, enabling new ways to teach and learn. With tools like online courses, digital textbooks, and educational apps, students now have access to information at their fingertips. Teachers can use multimedia to enhance lessons and engage students more effectively. Virtual classrooms and video conferencing have made remote learning a viable option for many. Additionally, technology allows students to collaborate and communicate in real-time, breaking down geographical barriers. The future of education will likely rely even more heavily on technological advancements to support learning.",
                "Regular exercise has numerous benefits for both physical and mental health. It helps improve cardiovascular health, boosts the immune system, and promotes weight management. Exercise also releases endorphins, which improve mood and reduce stress. Additionally, regular physical activity can improve sleep patterns and increase energy levels. Engaging in activities such as walking, running, or cycling can help maintain joint flexibility and reduce the risk of chronic diseases. Incorporating exercise into daily life can also improve focus and productivity, making it an essential part of a healthy lifestyle.",
                "Good nutrition is essential for maintaining overall health and well-being. A balanced diet provides the body with essential nutrients like vitamins, minerals, proteins, and healthy fats. These nutrients are necessary for energy production, immune function, and cellular repair. Proper nutrition also helps manage weight, improve cognitive function, and reduce the risk of chronic diseases like heart disease, diabetes, and obesity. Eating a variety of whole foods such as fruits, vegetables, whole grains, and lean proteins ensures that the body receives the necessary nutrients for optimal functioning.",
                "Renewable energy sources such as solar, wind, and hydroelectric power are rapidly gaining importance as alternatives to fossil fuels. These sources of energy are clean, sustainable, and have minimal environmental impact. As technology advances, the cost of renewable energy production continues to decrease, making it more accessible to individuals and businesses alike. The shift to renewable energy is essential for reducing carbon emissions, combating climate change, and ensuring long-term energy security. As governments and organizations invest in renewable energy infrastructure, the future of energy generation is becoming increasingly green and sustainable.",
                "Social media has revolutionized communication, allowing people to connect, share ideas, and engage with a global audience. However, it also has negative impacts, such as promoting unrealistic beauty standards and fostering a culture of comparison. The constant flow of information on social media can contribute to anxiety and stress, especially among younger users. Despite these challenges, social media can also serve as a platform for advocacy, education, and social change. It’s important to be mindful of how social media affects mental health and to maintain a balanced relationship with these platforms.",
                "Reading books has numerous benefits that contribute to both personal and intellectual growth. Books provide a gateway to different worlds, allowing readers to immerse themselves in various genres, histories, and cultures. Reading enhances vocabulary, comprehension, and cognitive function. It encourages critical thinking and helps improve focus and concentration. Books can also reduce stress, as they offer a form of escapism. Whether reading fiction or non-fiction, books are an invaluable source of knowledge and entertainment that enrich our lives and broaden our understanding of the world.",
                "Artificial intelligence (AI) is revolutionizing the healthcare industry by improving diagnostics, treatment planning, and patient care. AI algorithms can analyze medical data, such as imaging scans, to detect patterns and identify diseases at early stages. This enables doctors to make more accurate and timely diagnoses. AI is also being used to personalize treatment plans based on individual patient data, improving outcomes. Additionally, AI-powered virtual assistants can help manage patient interactions, providing immediate advice and streamlining administrative tasks in hospitals and clinics. AI is enhancing the overall quality of healthcare.",
                "Traveling exposes individuals to different cultures, ideas, and experiences that broaden their perspectives. It allows people to explore new places, try new foods, and meet new people, contributing to personal growth and development. Traveling can also reduce stress, as it provides an opportunity to disconnect from daily routines and relax. Whether for leisure or business, travel fosters creativity, problem-solving, and adaptability. It also allows individuals to experience the beauty of the world, from landscapes to architectural marvels. Travel offers opportunities for adventure, education, and making lasting memories.",
                "Environmental conservation is crucial for preserving the planet's natural resources and biodiversity. Over-exploitation of natural resources and pollution have led to environmental degradation, threatening ecosystems and the well-being of all living organisms. Conservation efforts aim to protect endangered species, reduce waste, and minimize carbon emissions. By promoting sustainable practices, such as recycling and reducing energy consumption, we can help mitigate climate change. It is essential to recognize the interconnectedness of human activities and the environment to ensure a healthy, balanced ecosystem for future generations to enjoy.",
                "Globalization refers to the increasing interconnectedness of the world through trade, technology, and communication. It has brought about numerous benefits, including economic growth, cultural exchange, and access to new markets. However, globalization has also led to challenges such as income inequality, cultural homogenization, and environmental degradation. As businesses expand globally, they often face criticism for exploiting labor and resources in developing countries. While globalization has connected people from different backgrounds, it has also highlighted disparities and tensions that need to be addressed to ensure equitable development and sustainable growth.",
                "Learning a second language offers numerous cognitive, social, and professional benefits. It enhances brain function, improves memory, and boosts problem-solving abilities. Speaking multiple languages also opens doors to new cultural experiences, fostering a deeper understanding of different customs and traditions. In today’s globalized world, multilingualism is an asset in the job market, as it allows individuals to communicate with a broader range of people. Moreover, learning a new language can improve personal confidence and expand social networks. Overall, being bilingual or multilingual enriches both personal and professional lives.",
                "Education is the cornerstone of personal and societal development. It provides individuals with the knowledge and skills necessary to succeed in life and contribute to their communities. Education fosters critical thinking, creativity, and problem-solving abilities, enabling individuals to adapt to changing circumstances. On a societal level, education promotes social equality by providing opportunities for everyone, regardless of their background. It is through education that we address pressing global issues, from climate change to poverty. A well-educated population is essential for the progress and prosperity of any society.",
                "Mental health is just as important as physical health, yet it is often overlooked or stigmatized. Mental health awareness is essential for breaking down the stigma surrounding mental illness and encouraging individuals to seek help when needed. By increasing public understanding of mental health, we can promote early intervention, provide better support for those affected, and reduce the negative impact of mental disorders on individuals and communities. It’s important to recognize the signs of mental health issues and take proactive steps to foster a supportive, understanding environment for mental well-being.",
                "Social media has changed the way people interact and form relationships. It has allowed individuals to stay connected with friends and family, regardless of distance. However, it has also introduced challenges, such as the rise of cyberbullying, miscommunication, and unrealistic expectations. People often present idealized versions of their lives on social media, which can lead to feelings of inadequacy and comparison. Social media can also contribute to the erosion of face-to-face communication, as people spend more time interacting online rather than in person. Maintaining healthy boundaries with social media is essential for healthy relationships.",
                "The internet has evolved dramatically since its inception. What began as a research project has now become an integral part of daily life, connecting billions of people around the world. The internet has transformed communication, commerce, education, and entertainment. Social media platforms, e-commerce websites, and online learning tools have revolutionized how we interact and consume information. However, the growth of the internet has also raised concerns about privacy, cybersecurity, and the spread of misinformation. As the internet continues to evolve, it’s important to address these challenges while ensuring its benefits are accessible to everyone.",
                "Effective time management is key to achieving personal and professional goals. By organizing tasks and prioritizing them, individuals can complete work efficiently and avoid stress. Time management also allows for a healthy work-life balance, as it helps prevent procrastination and overwork. Techniques like the Pomodoro Technique, to-do lists, and setting clear deadlines can improve focus and productivity. By making the most of available time, individuals can create space for relaxation and personal growth, reducing burnout and increasing overall satisfaction. Time management is essential for success in today’s fast-paced world.",
                "Electric vehicles (EVs) are poised to play a major role in the future of transportation. With growing concerns about environmental impact and fossil fuel depletion, EVs provide a cleaner and more sustainable alternative to traditional gasoline-powered cars. Advances in battery technology are making electric cars more affordable, efficient, and accessible to consumers. EVs produce zero emissions, reducing air pollution and mitigating the effects of climate change. As governments implement stricter environmental regulations and incentives for EV adoption, the market for electric vehicles is expected to grow rapidly, transforming the automotive industry.",
                "Meditation offers a wide range of mental and physical benefits. It helps reduce stress, improve concentration, and promote emotional well-being. Regular meditation practice has been shown to lower blood pressure, improve sleep quality, and enhance cognitive function. It also promotes mindfulness, which encourages individuals to focus on the present moment rather than worrying about the past or future. Meditation can be practiced in many forms, from guided sessions to silent reflection. Whether through breathing exercises or visualization, meditation is a valuable tool for maintaining mental and physical health.",
                "Access to clean water is essential for survival, yet millions of people around the world lack this basic resource. Clean water is necessary for hydration, food preparation, sanitation, and disease prevention. Contaminated water can lead to a range of health issues, from gastrointestinal diseases to cholera. Governments, organizations, and individuals must work together to ensure equitable access to clean water, especially in underserved regions. Protecting water sources, improving sanitation infrastructure, and promoting water conservation are key steps in addressing the global water crisis and ensuring a healthy future for all.",
                "Urbanization is the process by which an increasing percentage of the population moves from rural to urban areas. While urbanization offers many opportunities, such as better employment, education, and healthcare, it also presents several challenges. Overcrowding, pollution, and inadequate infrastructure can strain cities, leading to issues like traffic congestion, poor air quality, and a lack of affordable housing. Additionally, rapid urban growth can contribute to environmental degradation and loss of biodiversity. To address these challenges, cities must adopt sustainable urban planning practices that prioritize green spaces, efficient public transportation, and renewable energy sources.",
            ];
        }

    }
}
